In [115]:
#Andrew Knickman
#ITEC 345
#Python Numpy Lab 2


import numpy as np
arr_rand = np.array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2])
print("Array: ", arr_rand)

index_gt5 = np.where(arr_rand > 5)
print("Positions where value > 5:",index_gt5)

Array:  [8 8 3 7 7 0 4 2 5 2]
Positions where value > 5: (array([0, 1, 3, 4], dtype=int64),)


In [116]:
arr_rand.take(index_gt5)

np.where(arr_rand>5,'gt5','le5')

array(['gt5', 'gt5', 'le5', 'gt5', 'gt5', 'le5', 'le5', 'le5', 'le5',
       'le5'], dtype='<U3')

In [117]:
print("Position of max value:",np.argmax(arr_rand))

Position of max value: 0


In [118]:
print("Position of min value:",np.argmin(arr_rand))

Position of min value: 5


In [119]:
path = "NumpyLab2DS.txt"
data = np.genfromtxt(path, delimiter=',', skip_header=1, dtype=None, encoding=None)
data[:3]

array([(18., 8, 307., 130, 3504, 12. , 70, 1, ' b"chevrolet chevelle malibu"'),
       (15., 8, 350., 165, 3693, 11.5, 70, 1, ' b"buick skylark 320"'),
       (18., 8, 318., 150, 3436, 11. , 70, 1, ' b"plymouth satellite"')],
      dtype=[('f0', '<f8'), ('f1', '<i4'), ('f2', '<f8'), ('f3', '<i4'), ('f4', '<i4'), ('f5', '<f8'), ('f6', '<i4'), ('f7', '<i4'), ('f8', '<U29')])

In [120]:
#np.savetxt("out.csv",data,delimiter=",")

In [121]:
np.save('myarray.npy',arr_rand)

In [122]:
arr_rand2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
np.savez('array.npz',arr_rand,arr_rand2)

In [123]:
a = np.load('myarray.npy')
print(a)

[8 8 3 7 7 0 4 2 5 2]


In [124]:
b = np.load('array.npz')
print(b.files)
b['arr_0']

['arr_0', 'arr_1']


array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2])

In [125]:
a = np.zeros([4,4])
b = np.ones([4,4])
print(a)
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [126]:
np.concatenate([a,b],axis=1)
np.hstack([a,b])
np.c_[a,b]

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [127]:
np.r_[[1,2,3],0,0,[4,5,6]]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [128]:
arr = np.random.randint(1,6,size=[8,4])
arr

array([[3, 2, 3, 2],
       [1, 4, 1, 4],
       [5, 1, 4, 2],
       [1, 1, 4, 3],
       [3, 4, 4, 2],
       [2, 3, 4, 2],
       [1, 3, 4, 5],
       [1, 5, 4, 4]])

In [129]:
np.sort(arr,axis=0)

array([[1, 1, 1, 2],
       [1, 1, 3, 2],
       [1, 2, 4, 2],
       [1, 3, 4, 2],
       [2, 3, 4, 3],
       [3, 4, 4, 4],
       [3, 4, 4, 4],
       [5, 5, 4, 5]])

In [130]:
x = np.array([1, 10, 5, 2, 8, 9])
sort_index = np.argsort(x)
print(sort_index)

[0 3 2 4 5 1]


In [131]:
x[sort_index]

array([ 1,  2,  5,  8,  9, 10])

In [132]:
sorted_index_1stcol = arr[:,0].argsort()
arr[sorted_index_1stcol]

array([[1, 4, 1, 4],
       [1, 1, 4, 3],
       [1, 3, 4, 5],
       [1, 5, 4, 4],
       [2, 3, 4, 2],
       [3, 2, 3, 2],
       [3, 4, 4, 2],
       [5, 1, 4, 2]])

In [133]:
arr[sorted_index_1stcol[::-1]]

array([[5, 1, 4, 2],
       [3, 4, 4, 2],
       [3, 2, 3, 2],
       [2, 3, 4, 2],
       [1, 5, 4, 4],
       [1, 3, 4, 5],
       [1, 1, 4, 3],
       [1, 4, 1, 4]])

In [134]:
lexsorted_index = np.lexsort((arr[:,1],arr[:,0]))
arr[lexsorted_index]

array([[1, 1, 4, 3],
       [1, 3, 4, 5],
       [1, 4, 1, 4],
       [1, 5, 4, 4],
       [2, 3, 4, 2],
       [3, 2, 3, 2],
       [3, 4, 4, 2],
       [5, 1, 4, 2]])