In [1]:
#Andrew Knickman
#ITEC 345
#Python Numpy Lab 1

In [2]:
import numpy as np
list1=[0,1,2,3,4]
arr1d=np.array(list1)
print(type(arr1d))
arr1d

<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4])

In [3]:
arr1d+2

array([2, 3, 4, 5, 6])

In [4]:
list2=[[0,1,2],[3,4,5],[6,7,8]]
arr2d = np.array(list2)
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
arr2d_f = np.array(list2, dtype='float')
arr2d_f

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [6]:
arr2d_f.astype('int')

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
arr2d_f.astype('int').astype('str')

array([['0', '1', '2'],
       ['3', '4', '5'],
       ['6', '7', '8']], dtype='<U11')

In [8]:
list3 = [[1,2,3,4],[3,4,5,6],[5,6,7,8]]
arr3 = np.array(list2,dtype='float')
arr3

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [9]:
arr3[:2,:2]

array([[0., 1.],
       [3., 4.]])

In [10]:
b = arr3 > 4
b

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [11]:
arr3[b]

array([5., 6., 7., 8.])

In [12]:
arr3[::-1,]

array([[6., 7., 8.],
       [3., 4., 5.],
       [0., 1., 2.]])

In [13]:
arr3[::-1,::-1]

array([[8., 7., 6.],
       [5., 4., 3.],
       [2., 1., 0.]])

In [14]:
arr3[1,1] = np.nan
arr3[1,2] = np.inf
arr3

array([[ 0.,  1.,  2.],
       [ 3., nan, inf],
       [ 6.,  7.,  8.]])

In [15]:
missing_bool = np.isnan(arr3) | np.isinf(arr3)
arr3[missing_bool] = -1
arr3

array([[ 0.,  1.,  2.],
       [ 3., -1., -1.],
       [ 6.,  7.,  8.]])

In [16]:
print("Mean value is:", arr3.mean())
print("Max value is:", arr3.max())
print("Min value is:", arr3.min())

Mean value is: 2.7777777777777777
Max value is: 8.0
Min value is: -1.0


In [17]:
print("Column wise min:",np.amin(arr3,axis=0))
print("Row wise min:",np.amin(arr3,axis=1))

Column wise min: [ 0. -1. -1.]
Row wise min: [ 0. -1.  6.]


In [18]:
np.cumsum(arr3)

array([ 0.,  1.,  3.,  6.,  5.,  4., 10., 17., 25.])

In [19]:
arr3a = arr3[:2,:2]
arr3a[:1,:1] = 100
arr3

array([[100.,   1.,   2.],
       [  3.,  -1.,  -1.],
       [  6.,   7.,   8.]])

In [20]:
arr3b = arr3[:2,:2].copy()
arr3b[:1,:1] = 101
arr3

array([[100.,   1.,   2.],
       [  3.,  -1.,  -1.],
       [  6.,   7.,   8.]])

In [21]:
arr3.reshape(4,3)

ValueError: cannot reshape array of size 9 into shape (4,3)

In [22]:
print(np.arange(5))
print(np.arange(0,10))
print(np.arange(0,10,2))
print(np.arange(10,0,-1))

[0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[10  9  8  7  6  5  4  3  2  1]


In [23]:
np.linspace(start=1,stop=50,num=10,dtype=int)
np.set_printoptions(precision=2)
np.logspace(start=1,stop=50,num=10,base=10)

array([1.00e+01, 2.78e+06, 7.74e+11, 2.15e+17, 5.99e+22, 1.67e+28,
       4.64e+33, 1.29e+39, 3.59e+44, 1.00e+50])

In [24]:
np.zeros([2,2])
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [25]:
a = [1,2,3]
print('Tile:', np.tile(a,2))
print('Repeat:',np.repeat(a,2))

Tile: [1 2 3 1 2 3]
Repeat: [1 1 2 2 3 3]


In [26]:
print(np.random.rand(2,2))
print(np.random.randn(2,2))
print(np.random.randint(0, 10, size=[2,2]))
print(np.random.random())

[[0.88 0.18]
 [0.39 0.84]]
[[-0.65 -0.62]
 [ 0.39  0.21]]
[[3 6]
 [7 9]]
0.22642357435824112


In [27]:
print(np.random.random(size=[2,2]))
print(np.random.choice(['a','e','i','o','u'], size=10))
print(np.random.choice(['a','e','i','o','u'], size=10, p=[0.3,.1,0.1,0.4,0.1]))

[[0.54 0.06]
 [0.43 0.84]]
['o' 'a' 'a' 'a' 'a' 'e' 'e' 'e' 'o' 'i']
['u' 'o' 'o' 'o' 'o' 'a' 'i' 'o' 'o' 'o']


In [28]:
rn = np.random.RandomState(100)
print(rn.rand(2,2))
np.random.seed(100)
print(np.random.rand(2,2))

[[0.54 0.28]
 [0.42 0.84]]
[[0.54 0.28]
 [0.42 0.84]]


In [29]:
np.random.seed(100)
arr_rand = np.random.randint(0,10,size=10)
print(arr_rand)
uniqs, counts = np.unique(arr_rand, return_counts=True)
print("Unique Items:",uniqs)
print("Counts:",counts)

[8 8 3 7 7 0 4 2 5 2]
Unique Items: [0 2 3 4 5 7 8]
Counts: [1 2 1 1 1 2 2]
